-
  branches:
    only:
      - master

  version: 6.1.9
  install:
    - ps : .\environment-install.ps1

  assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    file: AssemblyInfo.*
    patch: true

  image: Visual Studio 2017

  before_build:
    - ps : .\build-before_build.ps1

  build:
    parallel: true
    verbosity: normal

  after_build:
    - ps : dotnet pack .\src\CompaniesHouse\CompaniesHouse.csproj -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION

  environment:
    CompaniesHouseApiKey:
      secure: MyplhKXpS1d9yob+xCzzJvgePFVi4ts5sPuMGWS7k6mOnVl1EcDAR+mpGOSSQWUQ

  configuration: Release

  cache:
    - packages -> **\packages.config
    - C:\downloads -> appveyor.yml

  test:
    assemblies:
      - '**\*.Tests.dll'
      - '**\*.FunctionalTests.dll'
      - '**\*.IntegrationTests.dll'
      - '**\*.ScenarioTests.dll'

  artifacts:
    - path: '**\bin\**\*.nupkg'

  deploy:
    - provider: Environment
      name: NuGet.org

-
  branches:
    except:
      - master

  version: 0.0.0-{branch}{build}

  install:
    - ps : .\environment-install.ps1

  assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    file: AssemblyInfo.*
    patch: true

  image: Visual Studio 2017

  before_build:
    - ps : .\build-before_build.ps1

  build:
    parallel: true
    verbosity: normal

  after_build:
    - ps : dotnet pack .\src\CompaniesHouse\CompaniesHouse.csproj -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION

  environment:
    CompaniesHouseApiKey:
      secure: MyplhKXpS1d9yob+xCzzJvgePFVi4ts5sPuMGWS7k6mOnVl1EcDAR+mpGOSSQWUQ

  configuration: Release

  cache:
    - packages -> **\packages.config
    - C:\downloads -> appveyor.yml

  test:
    assemblies:
      - '**\*.Tests.dll'
      - '**\*.FunctionalTests.dll'
      - '**\*.IntegrationTests.dll'

  artifacts:
    - path: '**\bin\**\*.nupkg'
